name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log out of Docker (to avoid caching)
        run: docker logout

      - name: Debug Secret Length
        run: |
          echo "Username length: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_USERNAME.length || 0 }}"
          echo "Password length: ${{ secrets.DOCKER_PASSWORD && secrets.DOCKER_PASSWORD.length || 0 }}"

      - name: Log in to Docker Hub (Password via stdin)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin registry-1.docker.io

      - name: Debug Docker Login (Direct Password, more verbose)
        run: docker login -D -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}" registry-1.docker.io

      - name: Build and Push Docker Image
        run: |
          docker build -t khuntia1994/wisecow:latest .
          docker push khuntia1994/wisecow:latest

      - name: Configure Kubernetes and Deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl set image deployment/wisecow-deployment wisecow-container=khuntia1994/wisecow:latest --record
          kubectl rollout status deployment/wisecow-deployment
          kubectl get pods -o wide
