name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t khuntia1234/wisecow:latest .
          docker push khuntia1234/wisecow:latest

      - name: Configure Kubernetes and Deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          
          kubectl set image deployment/wisecow-deployment wisecow-container=khuntia1234/wisecow:latest --record
          kubectl rollout status deployment/wisecow-deployment
          
          kubectl get pods -o wide
