name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log out from Docker to avoid caching issues
      - name: Log out of Docker (to avoid caching)
        run: docker logout

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Debugging Docker login to confirm credentials are correct
      - name: Debug Docker Login
        run: |
          docker info
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t khuntia1994/wisecow:latest .
          docker push khuntia1994/wisecow:latest

      # Configure Kubernetes and Deploy
      - name: Configure Kubernetes and Deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl set image deployment/wisecow-deployment wisecow-container=khuntia1994/wisecow:latest --record
          kubectl rollout status deployment/wisecow-deployment
          kubectl get pods -o wide

